package com.example.superkingsale.ui

import android.app.Activity
import android.print.PrintAttributes
import android.print.PrintManager
import android.webkit.WebView
import android.webkit.WebViewClient
import com.example.superkingsale.data.Record
import com.example.superkingsale.ui.LocalizedDialogBuilder as MaterialAlertDialogBuilder

/** WebView is used only as Android's HTML-to-print renderer, never for application navigation. */
object InvoicePrinter {
    fun escape(text: String) = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        .replace("\"", "&quot;").replace("'", "&#39;")
    fun document(sale: Record, branding: Record, paper: String = "a4", translate: (String) -> String = { it }): String {
        fun e(text: String) = escape(text)
        fun t(text: String) = e(translate(text))
        fun amount(key: String) = e(money(sale.number(key)))
        val logo = branding.text("logo_url").takeIf {
            runCatching { java.net.URI(it).let { uri -> uri.scheme == "https" && uri.host == "www.superkingmyanmar.com" && uri.userInfo == null } }.getOrDefault(false)
        }
        val customer = sale.obj("customer")
        val configuredFooter = branding.text("invoice_footer")
        val footerParts = buildList {
            if (configuredFooter.isNotBlank()) add(configuredFooter)
            if (!configuredFooter.contains("ကြီးပွားတိုးတက်ကြပါစေ")) add("ကြီးပွားတိုးတက်ကြပါစေ")
            if (!configuredFooter.contains("Generated by Royal Myanmar King Company Limited", ignoreCase = true))
                add("Generated by Royal Myanmar King Company Limited")
        }
        val lines = sale.rows("items").mapIndexed { index, line ->
            "<tr><td>${index + 1}</td><td class='product'><b>${e(line.obj("product").name)}</b><small>${e(line.obj("product").text("sku"))}</small></td>" +
                "<td>${line.number("quantity")}<small>${e(line.obj("unit").name)}</small></td>" +
                "<td>${if (line.number("foc_quantity") == 0L) "—" else line.number("foc_quantity").toString()}<small>${if (line.number("foc_quantity") == 0L) "" else e(line.obj("foc_unit").name)}</small></td>" +
                "<td class='amount'>${e(money(line.number("unit_price")))}</td>" +
                "<td class='amount'>${if (line.number("discount_amount") == 0L) "—" else e(money(line.number("discount_amount")))}</td>" +
                "<td class='amount strong'>${e(money(line.number("line_total")))}</td></tr>"
        }
        return """<!DOCTYPE html><html><head><meta charset="utf-8"><style>
            *{box-sizing:border-box}body{font:10px Arial,sans-serif;color:#172033;margin:0;overflow-wrap:anywhere;background:#fff}
            .page{padding:18px 20px;min-height:270mm}.brand{display:flex;justify-content:space-between;align-items:flex-start}
            .brand-left{display:flex;gap:10px;align-items:center}.logo{width:42px;height:42px;object-fit:contain}
            h1{font-size:18px;margin:0 0 3px}.tag{font-size:7px;color:#64748b;text-transform:uppercase}.invoice{text-align:right}
            .invoice h2{font-size:25px;letter-spacing:2px;margin:0}.reference{font-size:11px;font-weight:bold}.status{display:inline-block;color:#087b50;border:1px solid #87c9ad;border-radius:12px;padding:2px 7px;margin-top:5px;font-size:8px}
            .business{font-size:8px;color:#64748b;line-height:1.55;margin:12px 0 16px}.rule{height:2px;background:#ff8000;margin-bottom:16px}
            .details{display:grid;grid-template-columns:1.25fr 1fr;gap:24px;margin-bottom:20px}.label{font-size:7px;letter-spacing:1.2px;color:#64748b;font-weight:bold;text-transform:uppercase;margin-bottom:7px}
            .customer b{display:block;font-size:10px;margin-bottom:4px}.muted{color:#64748b;line-height:1.5}.meta{display:grid;grid-template-columns:1fr auto;gap:5px 12px}.meta span:nth-child(odd){color:#64748b}.meta span:nth-child(even){text-align:right;font-weight:bold}
            table{width:100%;border-collapse:collapse;table-layout:fixed}th{font-size:7px;letter-spacing:1px;color:#64748b;text-transform:uppercase;text-align:left;padding:7px 5px;border-bottom:1px solid #d9e0e7}
            td{padding:10px 5px;vertical-align:top;border-bottom:1px solid #eef1f4}th:first-child,td:first-child{width:4%}.product{width:31%}.product b{display:block;font-size:9px}.product small,td small{display:block;color:#64748b;font-size:7px;margin-top:3px}.amount{text-align:right;white-space:nowrap}.strong{font-weight:bold}
            .totals{width:43%;margin:12px 0 0 auto}.total-row{display:grid;grid-template-columns:1fr 110px;gap:12px;padding:6px 4px;text-align:right}.total-row span:last-child{font-weight:bold}
            .payable-wide{width:100%;border-top:2px solid #172033;margin-top:5px;padding:10px 4px 0;display:grid;grid-template-columns:1fr minmax(110px,22%) 110px;gap:12px;text-align:right;font-size:13px;font-weight:bold}.payable-wide .payable-label{grid-column:2}.payable-wide .payable-value{grid-column:3}
            .void{color:#b42318;border:2px solid #b42318;padding:5px 9px;font-weight:bold}.notes{margin-top:12px;color:#64748b}
            .signatures{display:grid;grid-template-columns:1fr 1fr;gap:80px;margin:65px 70px 0;text-align:center;color:#64748b;break-inside:avoid}.signature-line{border-top:1px solid #64748b;padding-top:6px}
            .footer{margin-top:42px;text-align:center;color:#7b8798;font-size:7px;line-height:1.6}
            .a5{font-size:9px}.a5 h1{font-size:17px}.a5 h2{font-size:12px}.a5 p{line-height:1.35;margin:8px 0}
            .a5 td{padding:5px 0}.a5 .total{font-size:14px}.a5 .signatures{margin-top:16px}
            .thermal{font-size:9px;width:${when(paper) { "50mm" -> "46mm"; "58mm" -> "54mm"; else -> "76mm" }};max-width:100%}.thermal h1{font-size:14px}.thermal h2{font-size:11px}
            .thermal p{line-height:1.35;margin:6px 0}.thermal .total{font-size:12px}
            .thermal .page{padding:2mm;min-height:0}.thermal .details,.thermal .signatures{display:block;margin:10px 0}.thermal .brand{display:block}.thermal .invoice{text-align:left;margin-top:8px}.thermal table,.thermal tr,.thermal td,.thermal th{display:block;width:100%;text-align:left}.thermal th{display:none}.thermal td{padding:3px 0;border:0}
            .thermal td.amount{text-align:right;border-bottom:1px dashed #526964}
            .thermal .signatures{margin-top:16px}.thermal .totals{width:100%}.thermal .payable-wide{grid-template-columns:1fr auto}.thermal .payable-wide .payable-label{grid-column:1}.thermal .payable-wide .payable-value{grid-column:2}.narrow{font-size:8px}
            @page{size:${if (paper == "a5") "A5" else "A4"};margin:8mm}@media print{body{margin:0}tr{break-inside:avoid}.page{min-height:auto}}
            </style></head><body class="${when(paper) { "a5" -> "a5"; "80mm" -> "thermal"; "58mm", "50mm" -> "thermal narrow"; else -> "a4" }}"><div class="page">
            <div class="brand"><div><div class="brand-left">${logo?.let { "<img class='logo' alt='' src='${e(it)}'>" }.orEmpty()}<div><h1>${e(branding.text("business_name", "Royal Myanmar King Company Limited"))}</h1><div class="tag">${e(branding.text("business_tagline", "Inventory & Sale"))}</div></div></div>
            <div class="business">${e(branding.text("business_address", sale.obj("warehouse").text("address")))} · ${e(branding.text("business_phone", sale.obj("warehouse").text("phone")))} · ${e(branding.text("business_email"))}</div></div>
            <div class="invoice"><h2>${t("INVOICE")}</h2><div class="reference">${e(sale.text("reference"))}</div><div class="status">${t(sale.text("status").uppercase())}</div></div></div><div class="rule"></div>
            ${if (sale.text("status") == "voided") "<p class='void'>${t("VOID")}: ${e(sale.text("void_reason"))}</p>" else ""}
            <div class="details"><div class="customer"><div class="label">${t("Bill to")}</div><b>${e(customer.name)}</b><div class="muted">${e(customer.text("code"))}<br>${e(customer.text("phone"))}<br>${e(customer.text("address"))}</div></div>
            <div class="meta"><span>${t("Invoice date")}</span><span>${e(sale.text("posted_at", sale.text("created_at")))}</span><span>${t("Payment")}</span><span>${t(sale.text("payment_type"))} · ${e(sale.text("payment_method_name"))}</span><span>${t("Representative")}</span><span>${e(sale.obj("representative").name)}</span><span>${t("Coverage")}</span><span>${e(sale.obj("region").name)}</span></div></div>
            <table><thead><tr><th>#</th><th>${t("Product")}</th><th>${t("Sold")}</th><th>${t("FOC")}</th><th class="amount">${t("Unit price")}</th><th class="amount">${t("Discount")}</th><th class="amount">${t("Amount")}</th></tr></thead><tbody>${lines.joinToString("")}</tbody></table>
            <div class="totals"><div class="total-row"><span>${t("Gross")}</span><span>${amount("gross_amount")}</span></div><div class="total-row"><span>${t("Item discounts")}</span><span>-${amount("total_discount")}</span></div><div class="total-row"><span>${t("Promotion cashback")}</span><span>-${amount("promotion_amount")}</span></div><div class="total-row"><span>${t("Cashback amount")}</span><span>-${amount("cashback_amount")}</span></div><div class="total-row"><span>${t("Item promotions")}</span><span>-${amount("total_item_promotion")}</span></div></div><div class="payable-wide"><span class="payable-label">${t("Payable total")}</span><span class="payable-value">${amount("total_amount")}</span></div>
            ${sale.text("notes").takeIf { it.isNotBlank() }?.let { "<div class='notes'><b>${t("Notes")}</b><br>${e(it)}</div>" }.orEmpty()}
            <div class="signatures"><div class="signature-line">${t("Customer signature")}</div><div class="signature-line">${t("Authorized signature")}</div></div>
            <div class="footer">${footerParts.joinToString(" · ") { e(it) }}</div></div></body></html>"""
    }
    fun print(activity: Activity, sale: Record, branding: Record, userId: Long, thermal: (() -> Unit)? = null) {
        val prefs = activity.getSharedPreferences("appearance", Activity.MODE_PRIVATE)
        val options = arrayOf("a4", "a5", "80mm", "58mm", "50mm")
        val labels = arrayOf("A4", "A5", "80 mm", "58 mm", "50 mm")
        var selected = options.indexOf(prefs.getString("paper.$userId", "a4")).coerceAtLeast(0)
        MaterialAlertDialogBuilder(activity).setTitle(activity.tr("Print invoice"))
            .setNeutralButton(if (thermal == null) "Paper size help" else "Connection / PDF") { _, _ ->
                if (thermal != null) { thermal(); return@setNeutralButton }
                MaterialAlertDialogBuilder(activity).setTitle("Paper size help")
                    .setMessage("Thermal sizes require a compatible print service. Check the paper size in Android's preview; unsupported sizes may fall back to Letter or A4.")
                    .setPositiveButton("OK", null).show()
            }
            .setSingleChoiceItems(labels, selected) { _, index -> selected = index }
            .setNegativeButton(activity.tr("Cancel"), null).setPositiveButton(activity.tr("Print / Save PDF")) { _, _ ->
                val paper = options[selected]
                prefs.edit().putString("paper.$userId", paper).apply()
                val web = WebView(activity)
                web.settings.javaScriptEnabled = false
                web.settings.allowFileAccess = false
                web.settings.allowContentAccess = false
                web.webViewClient = object : WebViewClient() {
                    private var launched = false
                    override fun shouldOverrideUrlLoading(view: WebView, request: android.webkit.WebResourceRequest) = true
                    override fun onPageFinished(view: WebView, url: String) {
                        if (launched) return
                        launched = true
                        if (activity.isFinishing || activity.isDestroyed) { web.destroy(); return }
                        val media = when (paper) {
                            "a5" -> PrintAttributes.MediaSize.ISO_A5
                            "80mm" -> PrintAttributes.MediaSize("80mm", "80 mm", 3150, 11693)
                            "58mm" -> PrintAttributes.MediaSize("58mm", "58 mm", 2283, 11693)
                            "50mm" -> PrintAttributes.MediaSize("50mm", "50 mm", 1969, 11693)
                            else -> PrintAttributes.MediaSize.ISO_A4
                        }
                        val delegate = web.createPrintDocumentAdapter(sale.text("reference"))
                        val adapter = object : android.print.PrintDocumentAdapter() {
                            override fun onStart() = delegate.onStart()
                            override fun onLayout(old: PrintAttributes?, new: PrintAttributes, signal: android.os.CancellationSignal,
                                callback: LayoutResultCallback, extras: android.os.Bundle?) = delegate.onLayout(old, new, signal, callback, extras)
                            override fun onWrite(pages: Array<out android.print.PageRange>, destination: android.os.ParcelFileDescriptor,
                                signal: android.os.CancellationSignal, callback: WriteResultCallback) = delegate.onWrite(pages, destination, signal, callback)
                            override fun onFinish() { delegate.onFinish(); web.destroy() }
                        }
                        runCatching {
                            val job = activity.getSystemService(PrintManager::class.java)?.print(sale.text("reference"), adapter,
                                PrintAttributes.Builder().setMediaSize(media).setMinMargins(PrintAttributes.Margins(79, 79, 79, 79))
                                    .setColorMode(PrintAttributes.COLOR_MODE_COLOR).build())
                            check(job != null) { "Printing is unavailable on this device." }
                        }.onFailure {
                            web.destroy()
                            android.widget.Toast.makeText(activity, activity.tr("Unable to open Android printing. Check that a print service is available."), android.widget.Toast.LENGTH_LONG).show()
                        }
                    }
                }
                web.loadDataWithBaseURL(null, document(sale, branding, paper, activity::tr), "text/html", "UTF-8", null)
            }.show()
    }
}
